### ISSUE TITLE
people: Two different alumni sections

### ISSUE THREAD

**Issue by dcallega** [uci-iasl/website#19]
We have two alumni sections: one is "handwritten" and the other is the automatically generated.
Is there an easy way to include Nadia in the alumni without making here profile?
Alternativaly, I would suggest calling her section the "Alumni before 2017"

**Comment by igorburago** [comment]
The only reason why we have the no-profile manual-entry Alumni section
on the People page is that Nadia have not contributed any information
for her personal page.

We could make a non-standard mechanism to automatically include
semi-manual alumni entries that do not correspond to personal pages
in the automatically generated section, but it would complicate things
unnecessarily, in my opinion.

Instead, I propose to make a minimal personal page for Nadia, and
eliminate the only exception. It does not have to be comprehensive;
for instance, I would be fine with something like #20.
