### ISSUE TITLE
bib: Should published papers retain links to (and BibTeX details of) their preprints?

### ISSUE THREAD

**Issue by igorburago** [uci-iasl/website#36]
Starting with #34, we began sharing preprints of papers that are
not yet accepted for publication. Naturally, this brings up the question
of whether we would like to keep the links to the preprints for the
papers published in their conferences’ proceedings. In other words,
in general, should the DOI-based link (once it is available) supersede,
say, the arXiv-based preprint link, or should we keep the latter around
when we add the former, and show both of them next to the entry?

At the moment (see the [ee91827 commit][c]), we implement the former
approach. Namely, the “Release” link points to the preprint page (e.g.,
on arxiv.com) until the DOI is added, at which point the same “Release”
link starts to point to the DOI-defined URL, instead, and the preprint
link, thus, goes away. This is because, in a way, the fact of final
publication makes the preprint stale (especially when we also release
the PDF on our website, so that the user does not need to rely on the
arXiv page even as the storage to obtain the PDF of the paper from).

[c]: https://github.com/uci-iasl/website/commit/ee9182718403928383913402abfd708a24dd41cb#diff-017a6aba3aa515074c154ae16a7b929bR20-R31

The same question goes for the preprint link information in the BibTeX
record, as well: Should we keep those fields (`eprint`, `eprinttype` and
its alias `archiveprefix`, `eprintclass` and its alias `primaryclass`) once
we update the record to the proper proceedings or journal citation?

Superficially, keeping the information does not seem to hurt. On the
other hand, though, those fields, strictly speaking, point to a different
document, a different version of the paper than the publisher’s version
released in the proceedings or the journal that are cited, and therefore
should be removed as conflicting.

This issue is to collect opinions on the matter. I am personally inclined
in favor of following the removal logic at the moment, but it is in no way
the definitive view.

**Comment by dcallega** [comment]
I agree with all the points raised, and the final conclusion: they should be removed.
A similar point to what you are making is about keeping the BibTeX clean for easy reference. If we leave too many details, it might be corrupted when used in a paper (depending on the bibliography style).

The way to do so is to enforce the rule of replacing the preprint links when we add the DOI to an entry. Correct?
However, since it is more of a policy than a semantic rule, I would not embed any checks in the BibTeX parser. What do you think?
